apirest/urls.py
from django.conf.urls import url
from apirest.views import *


urlpatterns = [
    url(r'^informes/$', InformeList.as_view(), name='informes')
]

django_shoppy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^products/', include('products.urls', namespace="products")),
    url(r'^login/', include('login.urls', namespace="login")),
    url(r'^api/v1/', include('apirest.urls', namespace="apirest")),
    url(r'^api/v1/auth', include('rest_framework.urls', namespace="rest_framework")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^hello', views.hello, name="hello"),
    url(r'^logout$', auth_views.logout, {'next_page':'/login'}, name="logout"),
    url(r'^', views.authentication, name="login"),
]

products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ProductList.as_view(), name="list"),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.ProductDetail.as_view(), name="detail"),
    url(r'^new', views.new_product, name="new_product"),
]

apirest/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Informe(models.Model):
    title = models.CharField(max_length=255)
    file_type = models.CharField(max_length=4)

clients/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Client(models.Model):
    name = models.CharField(max_length=255, blank=False)
    phone = models.IntegerField(blank=True)
    email = models.EmailField(max_length=255, blank=False)
    address = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id',)

login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

products/models.py
from __future__ import unicode_literals

from django.db import models
from clients.models import Client

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255, blank=False)
    description = models.CharField(max_length=255, blank=True)
    category = models.CharField(max_length=255, blank=False)
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=False)
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.name

    
    class Meta:
        ordering = ('id',)


class Favorite(models.Model):
    user = models.ForeignKey(Client)
    product = models.ForeignKey(Product)

    class Meta:
        verbose_name = 'Favorite'
        verbose_name_plural = 'Favorites'

    
    def __str__(self):
        return '%s %s' % (self.user.name, self.product.name)

products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = '__all__'

apirest/views.py
from rest_framework import generics
from .models import Informe
from .serializers import InformeSerializer
from django.shortcuts import get_object_or_404

class InformeList(generics.ListCreateAPIView):
    queryset = Informe.objects.all()
    serializer_class = InformeSerializer

    def get_object(self):
        queryset = self.get_queryset()
        obj = get_object_or_404(
            queryset,
            pk=self.kwargs['pk']
        )
        return obj

clients/views.py
from django.shortcuts import render

# Create your views here.

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# Create your views here.
def authentication(request):
    if request.method == 'POST':
        action = request.POST.get('action', None)
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)

        if action == 'sign-in':
            user = authenticate(username=username, password=password)
            login(request, user)
        elif action == 'sign-up':
            user = User.objects.create_user(username=username, password=password)
        return redirect('/login/hello')

    return render(request, 'login.html', {})


def hello(request):
    return render(request, 'hello.html', {})

products/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.shortcuts import render, get_object_or_404

from django.views.generic import ListView
from django.views.generic.detail import DetailView

from .forms import ProductForm
from .models import Product
from .mixins import LoginRequiredMixin

@login_required()
def new_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            product.save()
            return HttpResponseRedirect('/products')
    else:
        form = ProductForm()

    template = loader.get_template('new.html')
    form = ProductForm()
    context = {
        'form': form
    }
    return HttpResponse(template.render(context, request))


class ProductList(ListView):
    model = Product

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product

login/templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        {% load staticfiles %}
        <meta charset="UTF-8">
        <title>{% block title %} {% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
        <section>
            {% block content %} {% endblock %}
        </section>
    </body>
</html>

login/templates/hello.html
{% extends 'base.html' %}

{% block title %}
    Hello {% if user.is_authenticated %} {{user.username}} {% endif %}
{% endblock %}

{% block content %}
    <h1>Hello {% if user.is_authenticated %} {{user.username}} {% endif %}</h1>
    {% if user.is_authenticated %}
        <a href="{% url "login:logout" %}">Log out</a>
    {% endif %}

{% endblock %}

login/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Sing in | Sing up
{% endblock %}

{% block content %}
    <h1>Sing in</h1>
    <form action="" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username">
        <label for="password">Password</label>
        <input type="password" name="password">
        <input type="hidden" name="action" value="sign-in">
        <button type="submit">Sign in</button>
    </form>

    <h2>Sign up</h2>
    <form action="" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username">
        <label for="password">Password</label>
        <input type="password" name="password">
        <input type="hidden" name="action" value="sign-up">
        <button type="submit">Sign up</button>
    </form>
{% endblock %}

products/templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        {% load staticfiles %}
        <meta charset="UTF-8">
        <title>{% block title %} {% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
        <header>Header</header>
        <section>
            {% block content %} {% endblock %}
        </section>
        <footer>
            Footer
        </footer>
    </body>
</html>

products/templates/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <img src="{{ product.image.url }}" alt="{{ product.name }}" />
    <h3>{{ product.name }}</a></h3>
    <p>{{ product.description }}</p>
    <a href="{% url 'products:list' %}">Volver</a>
{% endblock %}

products/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Productos
{% endblock %}

{% block content %}
    <a href="{% url 'products.views.new_product' %}">New product</a>
    <ul>
        {% for pr in product %}
            <li>
                <img src="{{ pr.image.url }}" alt="{{ pr.name }}" />
                <h3><a href="{% url 'products.views.product' pk=pr.pk %}">{{ pr.name }}</a></h3>
                <p>{{ pr.description }}</p>
                
            </li>
        {% endfor %}
    </ul>
{% endblock %}

products/templates/new.html
{% extends 'base.html' %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <h3>New Product</h3>
    <a href="{% url 'products:list' %}">Back</a>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <img src="{{ product.image.url }}" alt="{{ product.name }}" />
    <h3>{{ product.name }}</a></h3>
    <p>{{ product.description }}</p>
    <a href="{% url 'products:list' %}">Volver</a>
{% endblock %}

products/templates/products/product_list.html
{% extends 'base.html' %}

{% block title %}
    Productos
{% endblock %}

{% block content %}
    <a href="{% url 'products:new_product' %}">New product</a>
    <ul>
        {% for pr in object_list %}
            <li>
                <img src="{{ pr.image.url }}" alt="{{ pr.name }}" />
                <h3><a href="{% url 'products:detail' pr.id  %}">{{ pr.name }}</a></h3>
                <p>{{ pr.description }}</p>
                
            </li>
        {% endfor %}
    </ul>
{% endblock %}